# TODO set .env
spring:
  application:
    name: MyApps
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_HOST:27017}
      database: ${MONGODB_DATABASE:myapps}
      username: ${MONGODB_USERNAME:mongouser}
      password: ${MONGODB_PASSWORD:mongopwd}
      auto-index-creation: true
      uuid-representation: standard

# JWT secret key
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME:86400000}
  cookie:
    secure: false
    same-site: None
    domain: localhost
    path: /
