spring:
  profiles:
    active: dev
  application:
    name: MyJobsInfra
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls: ${MAIL_SMTP_STARTTLS:false}
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_HOST:27017}
      database: ${MONGODB_DATABASE:myjobs}
      username: ${MONGODB_USERNAME:mongouser}
      password: ${MONGODB_PASSWORD:mongopwd}
      auto-index-creation: true
      uuid-representation: standard
      replica-set-name: rs0
      # uri: "mongodb://mongouser:mongopwd@localhost:27017/myjobs?authSource=myjobs&replicatSet=rs0"

# JWT secret key
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME:86400000}
  cookie:
    secure: false
    same-site: Strict
    domain: localhost
    path: /

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          mongodb: DEBUG


google:
  recaptcha:
    secret: ${GOOGLE_RECAPTCHA_PRIVATE_KEY}
    always-valid: true

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}



application:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
  mail:
    from: ${APPLICATION_MAIL_FROM:noreply@locahost}
    from-name: ${APPLICATION_MAIL_FROM_NAME:MyJobs}
