# security
security:
  cookie:
    secure: true

spring:
  mail.properties.mail.debug: false
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME:mongouser}:${MONGODB_PASSWORD:mongopwd}@${MONGODB_HOST:localhost}/${MONGODB_DATABASE:myjobs}?retryWrites=true&w=majority
      ssl:
        enabled: true

logging:
  level:
    software:
      amazon:
        awssdk:
          services:
            s3: ${LOG_LEVEL_STORAGE:WARN}
