# security
security:
  cookie:
    secure: true


logging:
  level:
    org:
      springframework:
        security: WARN
        mail: WARN
        data:
          mongodb: WARN

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME:mongouser}:${MONGODB_PASSWORD:mongopwd}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:myjobs}?retryWrites=true&w=majority
      ssl:
        enabled: true